<?php
return array (
  'mzadycms' => 
  array (
    's1' => 
    array (
      'logo1' => '/template/mizhiady/statics/images/logo_blue.png',
      'logo3' => '/template/mizhiady/statics/images/favicon.png',
      'pic' => '/template/mizhiady/statics/images/loading.gif',
      'errorpic' => '/template/mizhiady/statics/images/load.gif',
      'loginpic' => '/template/mizhiady/statics/images/user/bg-user-light.jpg',
      'regpic' => '/template/mizhiady/statics/images/user/bg-user-dark.jpg',
      'themecolor' => '#2862e5',
      'searchwd' => '搜索电影、电视剧、综艺、动漫',
      'sm' => '本站所有内容均来自互联网分享站点所提供的公开引用资源，未提供资源上传、存储服务。rgb(217, 40, 40)',
    ),
    's2' => 
    array (
      'cdnjs' => '1',
      'daohangid' => '1,2,3,4,5',
      'pcdhicon' => '1',
      'iconmr' => 'iconfont icon-duanju',
      'num1' => '1',
      'icon1' => 'iconfont icon-dianying',
      'num2' => '2',
      'icon2' => 'iconfont icon-dianshi',
      'num3' => '3',
      'icon3' => 'iconfont icon-zongyi1',
      'num4' => '4',
      'icon4' => 'iconfont icon-dongman',
      'num5' => '5',
      'icon5' => 'iconfont icon-Bzhan',
      'num6' => '6',
      'icon6' => '',
      'num7' => '7',
      'icon7' => '',
      'APP1_on' => '1',
      'APP1_ico' => 'iconfont icon-APPxiazai',
      'APP1_text1' => 'APP',
      'APP1_text2' => 'APP下载',
      'APP1_url' => 'https://www.98dou.cn/5232.html',
      'dbdh' => '1',
      'slidetj' => '9',
      'slidenum' => '8',
      'slidspeed' => '1000',
      'slidedelay' => '5000',
      'slidediy1' => '1',
      'slidediy1name' => '自定义幻灯片1',
      'slidediy1fname' => '自定义幻灯片1',
      'slidediy1pic' => 'https://liangcang-material.alicdn.com/prod/upload/691e72aabdbb47b7b86f6384e0c0fd35.webp.jpg?x-oss-process=image/resize,w_2074/interlace,1/quality,Q_70',
      'slidediy1url' => 'https://www.98dou.cn/5232.html',
      'slidediy2' => '0',
      'slidediy2name' => '自定义幻灯片2',
      'slidediy2fname' => '自定义幻灯片2',
      'slidediy2pic' => 'https://liangcang-material.alicdn.com/prod/upload/e40e2420e39d4fb09afe460761d9ae53.webp.jpg?x-oss-process=image/resize,w_2074/interlace,1/quality,Q_70',
      'slidediy2url' => 'https://www.98dou.cn/5232.html',
      'slidediy3' => '1',
      'slidediy3name' => '自定义幻灯片3',
      'slidediy3fname' => '自定义幻灯片3',
      'slidediy3pic' => 'https://liangcang-material.alicdn.com/prod/upload/e40e2420e39d4fb09afe460761d9ae53.webp.jpg?x-oss-process=image/resize,w_2074/interlace,1/quality,Q_70',
      'slidediy3url' => 'https://www.98dou.cn/5232.html',
      'hot' => '1',
      'hottitle' => '正在热播',
      'hotnum' => '12',
      'hotlevels' => 'vod_hits_day',
      'zztuijian' => '1',
      'zztuijianheadline' => '站长推荐',
      'zztuijiansubheading' => '站长精心挑选热门推荐',
      'zztuijianlight' => '/template/mizhiady/statics/images/bannerL.png',
      'zztuijiandark' => '/template/mizhiady/statics/images/bannerN.png',
      'zztuijiannum' => '12',
      'zztuijianlevels' => '5',
      'logtype' => '1,2,3,4,5',
      'new' => '1',
      'newicon' => '0',
      'newiconcss' => '#FF0000',
      'newids' => 'parent',
      'mryj' => '1',
      'dbtop' => '0',
      'user' => '1',
      'shoucang' => '1',
      'comment' => '1',
      'gonggao' => '1',
      'gonggao_speed' => '10',
      'gonggao_noti' => '觅知爱电影模板演示站 - 不提供任何播放仅演示购买地址：https://www.98dou.cn/5232.html',
      'nav_hb' => '1',
      'navn1' => '1',
      'navn1_ico' => 'iconfont icon-dianying',
      'navn1_title' => '电影',
      'navn1idnum' => '1',
      'navn1idtypenum' => '5',
      'navn2' => '1',
      'navn2_ico' => 'iconfont icon-dianshi',
      'navn2_title' => '电视剧',
      'navn2idnum' => '2',
      'navn2idtypenum' => '5',
      'navn3' => '1',
      'navn3_ico' => 'iconfont icon-zongyi',
      'navn3_title' => '综艺',
      'navn3idnum' => '3',
      'navn3idtypenum' => '5',
      'navn4' => '1',
      'navn4_ico' => 'iconfont icon-dongman',
      'navn4_title' => '动漫',
      'navn4idnum' => '4',
      'navn4idtypenum' => '5',
    ),
    's5' => 
    array (
      'wapsydh' => '1',
      'wapdaohangid' => '1,2,3,4,5',
      'wapiconmr' => 'iconfont icon-dianying',
      'wapnum1' => '1',
      'wapicon1' => 'iconfont icon-dianying',
      'wapnum2' => '2',
      'wapicon2' => 'iconfont icon-dianshi',
      'wapnum3' => '3',
      'wapicon3' => 'iconfont icon-zongyi1',
      'wapnum4' => '4',
      'wapicon4' => 'iconfont icon-dongman',
      'wapnum5' => '5',
      'wapicon5' => 'iconfont icon-Bzhan',
      'wapdiy1' => '0',
      'wapdiy1name' => 'APP',
      'wapdiy1url' => 'http://www.98dou.cn/',
      'wapdiy1icon' => 'iconfont icon-APPxiazai',
      'wapdiy2' => '0',
      'wapdiy2name' => 'APP2',
      'wapdiy2url' => 'http://www.98dou.cn/',
      'wapdiy2icon' => 'iconfont icon-APPxiazai',
    ),
    's6' => 
    array (
      'wapdaohangid' => 'parent',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
    ),
    's4' => 
    array (
      'ranktype' => '1,2,3,4,5',
      'anquanoff' => '1',
      'shier' => '1',
      'ctrl' => '1',
      'right' => '1',
      'mode' => '1',
      'pbtips' => '你知道的太多了',
      'tbdm' => '1',
      'tbdmtips' => '<meta name="referrer" content="always"> 
<meta name="referrer" content="no-referrer" />',
      'dbdm' => '1',
      'dbdmtips' => '',
      'stylediy' => '0',
      'stylecss' => '',
    ),
    's3' => 
    array (
      'adqj' => '1',
      'aadqj' => '<div class="item">
<a class="mizhiady-ad-img" href="https://www.98dou.cn/5232.html" target="_blank">
<img src="https://image.baidu.com/search/down?url=https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="全站通栏广告"></a></div>',
      'ad1' => '1',
      'aad1' => '<div class="item">
<a class="mizhiady-ad-img" href="https://www.98dou.cn/5232.html" target="_blank">
<img src="https://image.baidu.com/search/down?url=https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="首页广告"></a></div>',
      'ad2' => '1',
      'aad2' => '<div class="item">
<a class="mizhiady-ad-img" href="https://www.98dou.cn/5232.html" target="_blank">
<img src="https://m.ykimg.com/material/0A03/A1/202212/1221/3082837/1671604679858/0D01000063A2AAE50742279232473155.jpg" alt="详情页文字广告"></a></div>',
      'ad3' => '1',
      'aad3' => '<div class="item">
<a class="mizhiady-ad-img" href="https://www.98dou.cn/5232.html" target="_blank">
<img src="https://m.ykimg.com/material/0A03/A1/202212/1221/3082837/1671604679858/0D01000063A2AAE50742279232473155.jpg" alt="筛选页广告"></a></div>',
      'ad4' => '1',
      'aad4' => '<div class="item">
<a class="mizhiady-ad-img" href="https://www.98dou.cn/5232.html" target="_blank">
<img src="https://m.ykimg.com/material/0A03/A1/202212/1221/3082837/1671604679858/0D01000063A2AAE50742279232473155.jpg" alt="筛选页广告"></a></div>',
    ),
  ),
);